#!/bin/bash

# allow X11 access
xhost +local:docker

# start vscode
docker run -d \
  -d \
  -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
  -v ${HOME}/.config/Code:/developer/.config/Code \
  -v ${HOME}/.vscode:/developer/.vscode \
  -v ${HOME}/.ssh:/developer/.ssh \
  -v ${PWD}:/developer/project \
  -v ${SSH_AUTH_SOCK}:/ssh_auth_sock \
  -e SSH_AUTH_SOCK=/ssh_auth_sock \
  -e DISPLAY=unix${DISPLAY} \
  -p 5000:5000 \
  --device /dev/snd \
  --name vscode \
  sandangel/docker-vscode
